FORMAT: 1A


# UpSpain

PaynoPain UpSpain API



# Métodos de pago (payment_method):
+ UPACTIVA_CARD
+ PERSONAL_CARD
+ PERSONAL_CASH
+ COMPANY_CASH

# Tipos de factura (invoice_type):
+ INVOICE
+ TICKET


# Data Structures
## Data Object

### Purchase Receipt (object)
+ id
+ receipt_number
+ date
+ expediter_name
+ tax_identification_code
+ taxable_base
+ tax_rate
+ tax_fee
+ pdf
+ state
+ transaction_id
+ payment_method
+ paid (boolean)

### User (object)
+ id
+ external_id
+ first_name
+ last_name
+ roles (array)
+ commerces (array)


### Closure Purchase Receipt (object)
+ id (number) 
+ user_id - id interno de usuario
+ start_date - 2016-05-01T00:07:00+0000
+ end_date - 2016-05-31T00:07:00+0000
+ created_at
+ url

### Error Response (object)
+ error - Tipo del error
+ error_description - Descripción del error


## Responses
### Purchase Receipt Response (object)
+ id
+ receipt_number
+ date - 2016-05-31T00:07:00+0000
+ transaction_date - 2016-05-31T00:07:00+0000
+ expediter_name
+ tax_identification_code
+ taxable_base
+ tax_rate (number)
+ tax_fee (number)
+ pdf
+ description 
+ last_four_card_numbers
+ invoice_type
+ state
+ payment_method
+ paid (boolean)
+ transaction_id



# Resources

## Certificado [/certificate]
### Obtener un certificado validado [GET]

Para un usuario (ROLE_BENEFICIARY) devuelve el certificado que debe usar para firmar, en formato p12 o pem.

+ Request P12
    + Headers
    
            Authorization: Bearer XXXXXX
            Accept: application/x-pkcs12
+ Request PEM
    + Headers
    
            Authorization: Bearer XXXXXX
            Accept: application/x-pem-file         
            
            

+ Response 200 (application/x-pkcs12)
+ Response 200 (application/x-pem-file)
+ Response 400
+ Response 403
+ Response 422

## Notas de gasto [/purchase_receipt]
### Listar Notas de gasto [GET]
+ Request (application/json)
    + Attributes(object)
        + start_date 
        + end_date
        + transaction_type (string)
        + own_transactions (boolean)
        
    + Headers
            
            Authorization: Bearer XXXXXX
            x-page: 1
            x-page-size: 1000
        
        

+ Response 200 (application/json)
    + Attributes (array[Purchase Receipt])
    
    + Headers
    
            x-page: 1
            x-page-size: 1000
            x-page-total-results: 12



+ Response 200 (application/json)

### Crea una nueva Nota de Gasto [POST]


+ Request (application/json)
    + Attributes (object)
        + receipt_number 
        + date
        + transaction_date (required)
        + expediter_name (required)
        + tax_identification_code
        + taxable_base (number, required)
        + tax_rate (number)
        + tax_fee (number, required)
        + description
        + payment_method (required)
        + last_four_card_numbers
        + expense_type
        + pdf (required) - signed pdf base64 encoded 
        + invoice_type
        
    + Headers
            
            Authorization: Bearer XXXXXX

+ Response 201 (application/json)


## Nota de gasto [/purchase_receipt/{purchase_receipt_id}]


### Editar [PUT]

+ Request (application/json)
    + Parameters
        + purchase_receipt_id
    
    + Attributes (object)
        + receipt_number
        + date
        + expediter_name
        + tax_identification_code
        + taxable_base (number)
        + tax_rate (number)
        + tax_fee (number)
        + invoice_type
    
    + Headers
    
            Authorization: Bearer XXXXXX
            
+ Response 200 (application/json)
    + Attributes (object)
        + id
        + receipt_number
        + date
        + expediter_name
        + tax_identification_code
        + taxable_base (number)
        + tax_rate (number)
        + tax_fee (number)
        + invoice_type
    
    
    
## Digitalization To Pending [/purchase_receipt/{purchase_receipt_id}/state/pending]

### Convertir en Nota de gasto Pendiente [PUT]

+ Request (application/json)
    + Parameters
        + purchase_receipt_id
        
    + Attributes (object)
        + receipt_number (required)
        + tax_identification_code (required)
        + date (required)
        + tax_rate (required)
        + last_four_card_numbers (required)
    
        
    + Headers
    
            Authorization: Bearer XXXXXX
    
+ Response 200 (application/json)
        

    
## Estado de Notas de gasto [/purchase_receipt/{purchase_receipt_id}/state/refused]


### Rechazar Notas de gasto [PUT]
+ Request (application/json)
    + Parameters
        + purchase_receipt_id

    + Headers
            
            Authorization: Bearer XXXXXX
        
        

+ Response 200 (application/json)


### PDF de Nota de gasto [/purchase_receipt/{purchase_receipt_id}/pdf?access_token={access_token}]
## Obtener pdf de nota de gasto [GET]
+ Request (application/json)
    + Parameters
        + purchase_receipt_id
        + access_token
        
    

+ Response 200 (application/pdf)

## Abonos Nota de gasto [/purchase_receipt/{purchase_receipt_id}/paid]

### Marcar abonada [PUT]
+ Request (application/json)
    + Parameters
        + purchase_receipt_id
        
    + Headers
    
            Authorization: Bearer XXXXXX
            
+ Response 200 (application/json)
    + Attributes (Purchase Receipt)
        

### Notas de gasto por transacción [/purchase_receipts/transaction/{transaction_id}]
## Obtener [GET]
+ Request (application/json)
    + Attributes (object)
    + Headers
            
            Authorization: Bearer XXXXXX
+ Response 200 (application/json)
    + Attributes (Purchase Receipt Response)

## Cierres de Notas de gasto [/purchase_receipt_closure]

### Listar Cierres de Notas de Gasto [GET]
+ Request (application/json)
    + Attributes (object)

    + Headers
            
            Authorization: Bearer XXXXXX

+ Response 201 (application/json)
    + Attributes (array [Closure Purchase Receipt])

### Crea cierre de Notas de Gasto [POST]

+ Request (application/json)
    + Attributes
        + start_date (required)
        + end_date 
        + test (boolean) - si se pasa true, el cierre no tiene efecto. Sólo se obtendrá información.
        
    + Headers
            
            Authorization: Bearer XXXXXX
        
+ Response 201 (application/json)

## Cierre de Notas de gasto [/purchase_receipt_closure/{closure_id}]

### Eliminar cierre [DELETE]

Se borra el cierre y se reabren las notas de gasto que contiene, pasandolas a estado *STATE_PENDING*

+ Request (application/json)
    + Parameters
        + closure_id
    + Headers
        
            Authorization: Bearer XXXXXX
        
+ Response 204
+ Response 403
+ Response 422


## Recuperación de Cierre de Notas de Gasto [/purchase_receipt_closure/{closure_id}/recovery]
### Obtener las notas de gasto de un cierre [GET]

+ Request (application/json)
    + Parameters
        + closure_id
    + Headers
            
            Authorization: Bearer XXXXXX
            
+ Response 200 (application/json)
    + Attributes (array[Purchase Receipt])



## User [/user]
### Registrar usuario [POST]


+ Request (application/json)
    + Attributes
        + id (required) - id externa, refiere al usuario de upspain)
        + platform_type - WEB | APP
        
+ Response 201
    + Attributes (User)


## OAuth [/oauth/v2/token]

Opciones de ***grant_type***:
- **refresh_token**
- **client_credentials**
- **https://upspain-api.paynopain.com/grants/upspain**
    
    - Requerirá:
        - upspain_token
    

### Obtener Token [POST]
+ Request (application/json)
    + Attributes
        + grant_type: `https://upspain-api.paynopain.com/grants/upspain` (string)
        + `client_id`: 2_1keecruzdrk04ko444k0kcg8wwwggkkggss4scks8ss00ccgs4 (string)
        + client_secret: `1vyrfh9uxvwg40g04wo4gwcgkgokcwgkg4w80ccccgg488o4k8` (string)
        + upspain_token: xxxxx
        + platform_type : WEB - WEB | APP

+ Response 200 (application/json)
    + Attributes
        + access_token (string)
        + expires_in: 3600 (number)
        + token_type : bearer
        + scope: null
        + refresh_token (string)
        
+ Response 400
    Si la request está mal formada o los "client credentials" no son válidos

    + Attributes (Error Response)
    
+ Response 401
    Acceso no autorizado. Puede deberse a que el token de UpSpain no está autorizado por ellos.

    + Attributes (Error Response)
    
+ Response 403
    Acceso no permitido. No existe ningún usuario registrado que corresponda al usuario identificado.

    + Attributes (Error Response)